### ISSUE TITLE
Check the SODIMM-204 symbol versus JEDEC standard

### ISSUE THREAD

**Issue by jonnew** [open-ephys/open-ephys-kicad-library#1]
I would like a different set of eyes on this symbol to make sure it matches the JEDEC 4.20.18 - 204-Pin DDR3 SDRAM Unbuffered SO-DIMM Design Specification, pg. 9. 

https://github.com/open-ephys/open-ephys-kicad-library/blob/d3c637c917d6b90d7a55e052ff7f3a11bd596c9a/symbols/open-ephys.kicad_sym#L2

**Comment by cjsha** [comment]
The symbol's pin mapping matches jedec's pin mapping. I don't think this matters, but (just in case) this is what I noted about naming convention: 
- "_n" and "_c" are converted to "#"
- "_t" is omitted
- "S" is converted to "CS" for chip select pins
- Pins 83/107 are dual function or doubled labelled, which isn't indicated in the symbol
