### ISSUE TITLE
Review NRIC1384 pinout

### ISSUE THREAD

**Issue by jonnew** [open-ephys/open-ephys-kicad-library#2]
NRIC1384 is the BGA-packaged neuropixels 1.0 chip. It uses a 484 pin package. It needs a review to ensure pins are not misplaced. This is critical since this chip is so expensive.

**Comment by cjsha** [comment]
I couldn't find the pinout.. Can you link it here?

**Comment by jonnew** [comment]
I sent it your privately. Unfortunately, its not public in so far as I understand IMEC's sharing policy.

**Comment by cjsha** [comment]
GNIO -> GND_IO (or GND_I0 if you don't make the next change): R20
I0 -> IO: H21, H22, R21
VBAISP_BG -> VBIASP_BG: U20
VDD2AV -> VDDA2V: D22, E20, M1, W19, W22, V20
Only the first edit will actually change the resulting nets. The second edit I think is better for clarity maybe. The rest are just so they match the datasheet but won't actually change nets or anything else as far as putting together the schematic/pcb in kicad. They are not necessary, but I took note of them anyway just in case

**Comment by cjsha** [comment]
Can you close this issue when you commit the fixes?

**Comment by jonnew** [comment]
Thanks for the reminder, fixed in 324cb38.
